server:
  servlet:
    context-path: /cliente-veiculos/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver

h2:
  console:
    enabled: true
    path: /h2-console
